### ISSUE TITLE
Feature Selection

### ISSUE THREAD

**Issue by artanzand** [UBC-MDS/canadian_heritage_funding#17]
Should I categorize community type as an ordinal feature? See below. My logic is that the bigger the community, the higher the chances of getting higher funding.

ordinal = ["community_type"]
Comunity_order = ['Remote', 'Rural', 'Medium Urban', 'Small Urban', 'Large Urban']

**Comment by xiangwxt** [comment]
I agree, I think of it as the distance from large urban, or the scale of population.

**Comment by xiangwxt** [comment]
For the models, we can try 4 different models in the proposal, and select 1 or 2 for hyperparameter tunning.

**Comment by artanzand** [comment]
I think we need to change our target categories from 5 to 3. I am getting very low scores close to 50%

**Comment by jo4356** [comment]
I think maybe we should try dropping some of the features first and see what we get first, before changing the target. Maybe City column ?

**Comment by artanzand** [comment]
Ok, let me try

**Comment by artanzand** [comment]
Dropping city didn't improve it much

**Comment by artanzand** [comment]
And I think instead of recall we need to only focus on precision and f1 scores

**Comment by jo4356** [comment]
what about dropping project name also?

**Comment by artanzand** [comment]
Dropping neither of city, province or project_name improved the score
