### ISSUE TITLE
Folder for reports

### ISSUE THREAD

**Issue by jo4356** [UBC-MDS/canadian_heritage_funding#20]
Model selection ipynb file should not be in the src folder. Should we make a new folder for reports? We can also move the eda file in there.

**Comment by artanzand** [comment]
The two ipynb files for models are placeholders for now until we replace them with .py. We will delete them after.

**Comment by artanzand** [comment]
Reports will go inside the /doc folder and the images and tables that go inside the report will be stored in /results folder. This is how Tiffany's project does it. Let me know if this works.

**Comment by xiangwxt** [comment]
We can move files after the .py files have been created. ipynb files will be replaced eventually, no worries.
