### ISSUE TITLE
heritage_test.csv and heritage_train.csv column name

### ISSUE THREAD

**Issue by xiangwxt** [UBC-MDS/canadian_heritage_funding#24]
I found that the column name of the cleaned data is not the same as data used to train the best model. We need to follow the csv column names created. Maybe @artanzand check if we need to modify the final_model?

**Comment by xiangwxt** [comment]
I finalize the test score report. I dropped 3 columns to get the X_train based on columns of clean data. Please help check if there's any mistakes.

**Comment by artanzand** [comment]
I checked and adjusted the model. Thanks for the heads up!
