### ISSUE TITLE
Final report - highlights to include

### ISSUE THREAD

**Issue by aimee0317** [UBC-MDS/canadian_heritage_funding#31]
please comments on any highlights you believe must be included in the report.

**Comment by artanzand** [comment]
Under the title, can we fix the date so that we only see one date?

**Comment by artanzand** [comment]
- Do we need the C in front of Support Vector Classification in the first paragraph?
- I think we also need to mention the data size i.e. ~1300 observations

**Comment by artanzand** [comment]
Can you please change the funding size values in Table 01 to read:
- less than $8K
- $8 - 12 K
- $12-23K
- $23-50K
- over $50K

**Comment by xiangwxt** [comment]
Yes, I think this range is much clearer. I was confused without reading the context.

**Comment by xiangwxt** [comment]
We can change the target column class names in the clean.py

**Comment by aimee0317** [comment]
> Under the title, can we fix the date so that we only see one date?

One date is the date on which the report was created, the other is the date updated. They were the same initially, but will be different next time we update the report.

**Comment by aimee0317** [comment]
Variable name fixed in the report. Thank you guys for updating the script!

**Comment by aimee0317** [comment]
> * Do we need the C in front of Support Vector Classification in the first paragraph?
> * I think we also need to mention the data size i.e. ~1300 observations

I have updated "Support Vector Classification" it turned out C-Support Vector Classification is only specific to the SKLearn package and it's not the name for algorithm. 

We have a table included in the table that counts each category. I think this already provide the reader's a sense of our data size.
