### ISSUE TITLE
Draft Project Proposal

### ISSUE THREAD

**Issue by aimee0317** [UBC-MDS/canadian_heritage_funding#4]
**Tiff's example is** [here](https://github.com/ttimbers/breast_cancer_predictor/tree/v1.1)
**Requirements:**
Identify a data set, research question, & plan of action for analysis to answer that question
Choose a public data set from the web that you are interested in to carry out a small data analysis. You may also use any data set we have previously worked with in MDS. Correctly cite where your data set is coming from in your proposal. Be sure that it is a data set that is licensed to be shared and used openly on the internet.

With your data set, identify one main predictive or inferential research question that you will attempt to answer with analyses and visualizations (more on this below). Clearly state the research question and any natural sub-questions you need to address, and their type.

Make a plan of how you will analyze the data (report an estimate and confidence intervals? hypothesis test? classification with a decision tree?). Choose something you already learned how to do in another MDS course.

Discuss at least one exploratory data analysis (EDA) table and one exploratory data analysis figure you will create that makes sense for your research question, the data that you have, and the analysis you plan to do.

Suggest how you would share the results of your analysis as one or more tables and/or figures.

Note - Remember, if you have a predictive research question, it is essential that you separate your dataset before you do any analysis. To be clear, you should NOT do any analysis - including preliminary EDA - on your test data.

**Components we need for README.md:** 
- Introduction 
- Usage
- Dependencies
- License 
- References

**Comment by artanzand** [comment]
For the intro piece we could add to this material from the government website:
- Data on funding provided in 2016-2017 and 2017-2018 by the Canada Arts Presentation Fund, Canadian Heritage
- The Canada Arts Presentation Fund (CAPF) provides financial assistance to organizations that professionally present arts festivals or performing arts series (arts presenters) and organizations that offer support to arts presenters.

Publisher - Current Organization Name: Canadian Heritage
Publisher - Organization Section Name: Arts Branch, Cultural Affairs Sector

**Comment by jo4356** [comment]
Prediction problem: Predicting the class of amount_aproved. So far we are aggregating values into 5 classes based on quantiles, and we can discuss further which quantiles we want/ is appropriate.

Analyzing the data: Maybe try a few classifiers, such as naive bayes, SVC, logistic regression

**Comment by xiangwxt** [comment]
Are we going to say the purpose of the study is to predict future fund approval?

**Comment by aimee0317** [comment]
Google doc to draft and edit the proposal: https://docs.google.com/document/d/1KpcrRLxyAlvgYqSb5Yl55uWfyJM_HkPuvdElMKkFMi4/edit

**Comment by aimee0317** [comment]
README.md file edited based on the draft proposal. Need to add info on dependences and license. https://github.com/UBC-MDS/canadian_heritage_funding/blob/main/README.md

**Comment by aimee0317** [comment]
The final README.md file is here https://github.com/UBC-MDS/canadian_heritage_funding/blob/main/README.md. Please review.
