### ISSUE TITLE
Feature Selection

### ISSUE THREAD

**Issue by artanzand** [UBC-MDS/canadian_heritage_funding#48]
One method that we have been thinking about adding to our model in order to improve performance has been to do a feature selection exercise to remove unimportant features. However, thinking deeper into this and through prior experience in this project we won't be able to do so. This is mainly because of the (abundant) presence of categorical features in our dataset. Feature selection will remove some of the categories, and therefore, cause a fatal error when the model is run on the test data. This is a running issue with sklearn: https://github.com/scikit-learn/scikit-learn/issues/8480

**Comment by artanzand** [comment]
We might want to briefly mention this in the report in future iterations.

**Comment by aimee0317** [comment]
I saw the TA would like us to include more information on the feature we selected, either through literature or through a serious feature selection using code. On the report, I can certainly add more "literature"/reasoning based on common sense. Do we plan to conduct a feature selection using code?
