### ISSUE TITLE
run_all file redundant?

### ISSUE THREAD

**Issue by artanzand** [UBC-MDS/canadian_heritage_funding#54]
Thank you for the Makefile! Now that we have this file, I was wondering if we should be deleting the run_all.sh file?

**Comment by artanzand** [comment]
Also, we could update the README.md file by changing `bash run_all.sh` to `make all`

**Comment by aimee0317** [comment]
> Thank you for the Makefile! Now that we have this file, I was wondering if we should be deleting the run_all.sh file?

I think we can delete run_all.sh.

**Comment by aimee0317** [comment]
I included both in the README file so we can keep both. It's a good compromise!
