### ISSUE TITLE
Dockerfile

### ISSUE THREAD

**Issue by artanzand** [UBC-MDS/canadian_heritage_funding#65]
Since we use Rmd to create our final report, I have used jupyter/data_science docker image as our starting image. We could dig in later and remove any packages that we don't find necessary.

**Comment by aimee0317** [comment]
Yes, that's a great idea. data_science docker image as a starter is a great choice!

**Comment by artanzand** [comment]
We encountered an instance with the image file growing large and decided to start from jupyter/minimal_notebook and add required R and Py3 packages selectively.

**Comment by artanzand** [comment]
![Capture](https://user-images.githubusercontent.com/74034506/145504485-ae946747-a7b3-4b48-8934-5402e24eee43.JPG)
Creating the docker image, I encountered the above error saying that these packages could not be found through conda-forge channel. I will try creating the image without them, and if required, will add them at a later stage.

**Comment by xiangwxt** [comment]
Have you tried mamba or pip?

**Comment by artanzand** [comment]
mamba worked well with R packages and conda with Python packages.

**Comment by artanzand** [comment]
Instead of using `Rscript -e "install.packages("KableExtra")"` which was giving me errors on the CRAN website, I used the conda script `conda install r-kableextra` .
