### ISSUE TITLE
Feedback to work on

### ISSUE THREAD

**Issue by aimee0317** [UBC-MDS/canadian_heritage_funding#66]
We need to pick at least four feedback according to which we can make improvements on our project. Let's discuss!

**Comment by artanzand** [comment]
I find Andy's comment on the two README files valid. I think the .Rmd file could go. The downfall of not having an .Rmd is that bibliography is not automated anymore. However, `.md` read well and is native to GitHub.

**Comment by artanzand** [comment]
The other file that could be removed from the main directory is `run_all.sh` now that we have a Makefile.

**Comment by xiangwxt** [comment]
If we remove rmd file, how are we going to make it automated?

**Comment by jo4356** [comment]
there is a README.md file already.

One feedback we have already worked on is making the image in the final report higher resolution. The commit was  #3291034

**Comment by xiangwxt** [comment]
According to Jasmine's comment, we need to put specific contact email in the code of conduct. I will put my email address there. The commit no. is https://github.com/xiangwxt/canadian_heritage_funding/commit/07a0ed137aa9af08feefeb12fcdd0981d07bd766

**Comment by xiangwxt** [comment]
According to Jasmine's comment, 
Analysis: "Therefore, we selected random forest as the best performing model to conduct hyperparameter optimization and tuned max_features, max_depth" and "class_weight as well as the max_features argument in CountVectorizer()."
The issue has been revised, please see two commits below (there was a mistake in the first commit, and revised with the second one)
https://github.com/xiangwxt/canadian_heritage_funding/commit/2d643b72ba13496e98a3a159d62df50e4f5185b2
https://github.com/xiangwxt/canadian_heritage_funding/commit/c6e87dcfbf691d8d6f13a9fe4ef2a04f8a91d767

**Comment by xiangwxt** [comment]
TA Andy mentioned we need to add figure caption, I think we have already added in the rmd file, the thing is it could not be displayed on github_document.
